#FROM hub.vtcc.vn:8989/node

#WORKDIR /app

#COPY package*.json ./

#RUN npm config set https-proxy http://proxy.cyberspace.vn:3128
#RUN npm install
#RUN npm audit fix

#COPY . .

# Build the Vite project
#RUN npm run build

FROM hub.vtcc.vn:8989/nginx
RUN mkdir /app
COPY dist /var/www/html
COPY nginx.conf /etc/nginx/conf.d/default.conf


